name: Automatic Builds

on:
  push:
    branches:
    - master

jobs:

  build-mac:
    runs-on: macos-latest

    steps:
    - name: Install wxWidgets and PortAudio
      run: brew install wxmac portaudio
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        make -f Makefile.mac -j$(sysctl -n hw.logicalcpu)
        ./mac-bundle.sh --dmg
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: noods-mac
        path: NooDS.dmg

  build-switch:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: make -f Makefile.switch -j$(nproc)
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: noods-switch
        path: noods.nro

  build-wiiu:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        make -f Makefile.wiiu -j$(nproc)
        mv icon/icon-wiiu.png icon.png
        mv icon/meta.xml meta.xml
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: noods-wiiu
        path: |
          icon.png
          meta.xml
          noods.rpx

  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        make -f Makefile.wii -j$(nproc)
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: |
          build/
