name: Libogc2-ogx
on:
  push:
    branches:
    - master
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install FreeGLUT Prerequisites 
      run: |
        brew install cmake libx11 libxi libxrandr libxxf86vm pkg-config mesa
    - name: Install SDL2
      run: |
        mkdir build
        cd build
        git clone --branch SDL2 --depth 1 https://github.com/libsdl-org/SDL.git
        cmake sdl
        make
        sudo make install
    - name: Install FreeGLUT
      run: |
        cd .
        git clone https://github.com/freeglut/freeglut.git
        cd freeglut
        mkdir build && cd build
        cmake -DFREEGLUT_BUILD_DEMOS=OFF -DOPENGL_gl_LIBRARY=/opt/homebrew/lib/libGL.dylib ..
        make && sudo make install
      
    - name: Install dependencies extremscorner
      run: |
        sudo dkp-pacman-key --recv-keys C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE --keyserver keyserver.ubuntu.com
        sudo dkp-pacman-key --lsign-key C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE
        sudo sed -i '/^\[dkp-libs\]$/,$d' /opt/devkitpro/pacman/etc/pacman.conf
        sudo echo -e '[extremscorner-devkitpro]\nServer = https://packages.extremscorner.org/devkitpro/linux/$arch' >> /opt/devkitpro/pacman/etc/pacman.conf
        sudo dkp-pacman -Sy
        sudo dkp-pacman -S --noconfirm --ask 4 libogc2 libogc2-cmake libogc2-libfat-git libogc2-opengx libogc2-sdl2 libogc2-glu ppc-glm
    - name: Compile
      run: |
        cd wii-examples
        make -f Makefile.ogx
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: wii-directory-ocg2
        path: |
          ./wii-examples/*.dol
