name: Libogc-ogx
on:
  push:
    branches:
    - master
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies devkitpro
      run: |
        sudo dkp-pacman-key --recv BC26F752D25B92CE272E0F44F7FD5492264BB9D0 --keyserver keyserver.ubuntu.com
        sudo dkp-pacman-key --lsign BC26F752D25B92CE272E0F44F7FD5492264BB9D0
        sudo dkp-pacman -U --noconfirm --ask 4 https://pkg.devkitpro.org/devkitpro-keyring.pkg.tar.zst
        sudo dkp-pacman -Sy
        sudo dkp-pacman -S --noconfirm --ask 4 wii-opengx wii-glu wii-sdl2 wii-freeglut
    - name: Compile
      run: |
        cd wii-examples
        make -f Makefile.ogx-ogc
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: wii-directory
        path: |
          ./wii-examples/*.dol
