name: Libogc
on:
  push:
    branches:
    - master
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install SDL2
      run: |
        cd .
        git clone --single-branch ogc-sdl-2.28 https://github.com/devkitPro/SDL/tree/ogc-sdl-2.28.git
        cd ocg-sdl-2.28
        cmake -S. -Bbuild -DCMAKE_TOOLCHAIN_FILE="$DEVKITPRO/cmake/Wii.cmake"
        cd build
        make
        sudo -E PATH=$PATH make install

    - name: Install OpenGX
      run: |
        cd .
        git clone https://github.com/devkitPro/opengx.git
        cd opengx
        cmake -S. -Bbuild -DCMAKE_TOOLCHAIN_FILE="$DEVKITPRO/cmake/Wii.cmake"
        cd build
        make
        sudo -E PATH=$PATH make install

    - name: Install FreeGLUT
      run: |
        cd .
        git clone https://github.com/freeglut/freeglut.git
        cd freeglut
        mkdir build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE="$DEVKITPRO/cmake/Wii.cmake" -DFREEGLUT_BUILD_DEMOS=OFF ..
        make
        sudo -E PATH=$PATH make install

        
    - name: Compile
      run: |
        cd wii-examples
        make -f Makefile.ogx-ogc
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: wii-directory
        path: |
          ./wii-examples/*.dol
