name: Libogc2
on:
  push:
    branches:
    - master
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo dkp-pacman-key --recv-keys C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE --keyserver keyserver.ubuntu.com
        sudo dkp-pacman-key --lsign-key C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE
        sudo sed -i '/^\[dkp-libs\]$/,$d' /opt/devkitpro/pacman/etc/pacman.conf
        sudo echo -e '[extremscorner-devkitpro]\nServer = https://packages.extremscorner.org/devkitpro/linux/$arch' >> /opt/devkitpro/pacman/etc/pacman.conf
        sudo dkp-pacman -Sy
        sudo dkp-pacman -R --cascade libogc2-git
        sudo dkp-pacman -S --needed devkitPPC wii-tools ppc-libmad
        git clone https://github.com/extremscorner/libogc2.git
        cd libogc2
        make
        sudo -E make install
        git clone https://github.com/extremscorner/libfat.git
        cd libfat
        make ogc-release
        sudo -E make ogc-install   
    - name: Compile
      run: |
        cd wii-examples
        make -f Makefile.ocg2
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: wii-directory-ocg2
        path: |
          ./wii-examples/*.dol
