name: Libogc2
on:
  push:
    branches:
    - master
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo (dkp-)pacman -R --cascade libogc2(-git)
        sudo (dkp-)pacman -S --needed devkitPPC wii-tools ppc-libmad
        git clone https://github.com/extremscorner/libogc2.git
        cd libogc2
        make
        sudo -E make install
        git clone https://github.com/extremscorner/libfat.git
        cd libfat
        make ogc-release
        sudo -E make ogc-install   
    - name: Compile
      run: |
        cd wii-examples
        make -f Makefile.ocg2
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: wii-directory-ocg2
        path: |
          ./wii-examples/*.dol
