name: Libogc
on:
  push:
    branches:
    - master
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        cd wii-examples
        make -f Makefile.ogx-ogc
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: wii-directory
        path: |
          ./wii-examples/*.dol
