name: Libogc2-FixGB
on:
  push:
    branches:
    - main
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies extremscorner
      run: |
        sudo dkp-pacman-key --recv-keys C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE --keyserver keyserver.ubuntu.com
        sudo dkp-pacman-key --lsign-key C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE
        sudo sed -i '/^\[dkp-libs\]$/,$d' /opt/devkitpro/pacman/etc/pacman.conf
        sudo echo -e '[extremscorner-devkitpro]\nServer = https://packages.extremscorner.org/devkitpro/linux/$arch' >> /opt/devkitpro/pacman/etc/pacman.conf
        sudo dkp-pacman -Sy
        sudo dkp-pacman -S --noconfirm --ask 4 gamecube-tools-git libogc2-dkp-toolchain-vars ppc-libmad libogc2-git libogc2-cmake libogc2-libansnd-git libogc2-libdvm libogc2-opengx libogc2-glu libogc2-sdl2 
        # dkp-pacman -Ql  
        # old list 7-22-25
        # sudo dkp-pacman -S --noconfirm --ask 4 libogc2 libogc2-git gamecube-tools-git libogc2-dkp-toolchain-vars libogc2-cmake libogc2-libansnd-git libogc2-libdvm libogc2-opengx libogc2-glu libogc2-sdl2
        # _pkgname=SDL2 depends=('devkitPPC' 'libogc2' 'libogc2-libfat')
        # makedepends=('catnip' 'cmake' 'gamecube-cmake' 'git' 'libogc2-cmake' 'libogc2-opengx' 'wii-cmake')
        # optdepends=('libogc2-opengx: OpenGL support')
        
    - name: Compile
      run: |
        cd wii-examples
        make -f Makefile-fixGBv2.ogc2
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: wii-directory-ogc2
        path: |
          ./wii-examples/*.dol
